# Generated by Django 5.2.5 on 2025-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cart_compare_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
